require 'rearmed/monkey_patches/object'
require 'rearmed/monkey_patches/string'
require 'rearmed/monkey_patches/array'
require 'rearmed/monkey_patches/hash'
require 'rearmed/monkey_patches/enumerable'
require 'rearmed/monkey_patches/rails_3'
require 'rearmed/monkey_patches/rails_4'
require 'rearmed/monkey_patches/date'
